# Do not edit this file.  It is generated from:
#    /gpfs/dell2/emc/modeling/noscrub/Henrique.Alves/GFSv16/UFS/ufs-weather-model/coupledFV3_WW3.appBuilder
# Edit that file instead.
COMPONENTS ?= FMS FV3 WW3
