list(APPEND fms_src_files
    FMS/amip_interp/amip_interp.F90
    FMS/astronomy/astronomy.F90
    FMS/axis_utils/axis_utils.F90
    FMS/block_control/block_control.F90
    FMS/column_diagnostics/column_diagnostics.F90
    FMS/constants/constants.F90
    FMS/coupler/atmos_ocean_fluxes.F90
    FMS/coupler/coupler_types.F90
    FMS/coupler/ensemble_manager.F90
    FMS/data_override/data_override.F90
    FMS/diag_integral/diag_integral.F90
    FMS/diag_manager/diag_axis.F90
    FMS/diag_manager/diag_data.F90
    FMS/diag_manager/diag_grid.F90
    FMS/diag_manager/diag_manager.F90
    FMS/diag_manager/diag_manifest.F90
    FMS/diag_manager/diag_output.F90
    FMS/diag_manager/diag_table.F90
    FMS/diag_manager/diag_util.F90
    FMS/drifters/cloud_interpolator.F90
    FMS/drifters/drifters.F90
    FMS/drifters/drifters_comm.F90
    FMS/drifters/drifters_core.F90
    FMS/drifters/drifters_input.F90
    FMS/drifters/drifters_io.F90
    FMS/drifters/quicksort.F90
    FMS/exchange/stock_constants.F90
    FMS/exchange/xgrid.F90
    FMS/fft/fft.F90
    FMS/fft/fft99.F90
    FMS/field_manager/field_manager.F90
    FMS/field_manager/fm_util.F90
    FMS/fms/fms.F90
    FMS/fms/fms_io.F90
    FMS/horiz_interp/horiz_interp.F90
    FMS/horiz_interp/horiz_interp_bicubic.F90
    FMS/horiz_interp/horiz_interp_bilinear.F90
    FMS/horiz_interp/horiz_interp_conserve.F90
    FMS/horiz_interp/horiz_interp_spherical.F90
    FMS/horiz_interp/horiz_interp_type.F90
    FMS/interpolator/interpolator.F90
    FMS/memutils/memutils.F90
    FMS/monin_obukhov/monin_obukhov.F90
    FMS/monin_obukhov/monin_obukhov_kernel.F90
    FMS/mosaic/gradient.F90
    FMS/mosaic/grid.F90
    FMS/mosaic/mosaic.F90
    FMS/mpp/mpp.F90
    FMS/mpp/mpp_data.F90
    FMS/mpp/mpp_domains.F90
    FMS/mpp/mpp_efp.F90
    FMS/mpp/mpp_io.F90
    FMS/mpp/mpp_memutils.F90
    FMS/mpp/mpp_parameter.F90
    FMS/mpp/mpp_pset.F90
    FMS/mpp/mpp_utilities.F90
    FMS/platform/platform.F90
    FMS/random_numbers/MersenneTwister.F90
    FMS/random_numbers/random_numbers.F90
    FMS/sat_vapor_pres/sat_vapor_pres.F90
    FMS/sat_vapor_pres/sat_vapor_pres_k.F90
    FMS/station_data/station_data.F90
    FMS/time_interp/time_interp.F90
    FMS/time_interp/time_interp_external.F90
    FMS/time_manager/get_cal_time.F90
    FMS/time_manager/time_manager.F90
    FMS/topography/gaussian_topog.F90
    FMS/topography/topography.F90
    FMS/tracer_manager/tracer_manager.F90
    FMS/tridiagonal/tridiagonal.F90

    FMS/memutils/memuse.c
    FMS/mosaic/create_xgrid.c
    FMS/mosaic/gradient_c2l.c
    FMS/mosaic/interp.c
    FMS/mosaic/mosaic_util.c
    FMS/mosaic/read_mosaic.c
    FMS/mpp/nsclock.c
    FMS/mpp/threadloc.c
)

list( APPEND fms_headers 
FMS/mpp/include/mpp_do_global_field.h
FMS/mpp/include/mpp_read_distributed_ascii.h
FMS/mpp/include/mpp_transmit_mpi.h
FMS/mpp/include/mpp_write_unlimited_axis.h
FMS/mpp/include/mpp_write_2Ddecomp.h
FMS/mpp/include/mpp_reduce_sma.h
FMS/mpp/include/mpp_error_a_a.h
FMS/mpp/include/mpp_unstruct_pass_data.h
FMS/mpp/include/mpp_alltoall_nocomm.h
FMS/mpp/include/mpp_update_domains2D_ad.h
FMS/mpp/include/mpp_global_sum.h
FMS/mpp/include/mpp_sum_nocomm.h
FMS/mpp/include/mpp_do_checkV.h
FMS/mpp/include/mpp_write.h
FMS/mpp/include/mpp_do_get_boundary_ad.h
FMS/mpp/include/mpp_type_nocomm.h
FMS/mpp/include/mpp_type_sma.h
FMS/mpp/include/mpp_reduce_nocomm.h
FMS/mpp/include/mpp_do_update_ad.h
FMS/mpp/include/mpp_do_redistribute.h
FMS/mpp/include/mpp_do_updateV_ad.h
FMS/mpp/include/mpp_alltoall_sma.h
FMS/mpp/include/mpp_read_compressed.h
FMS/mpp/include/mpp_chksum.h
FMS/mpp/include/mpp_global_field_ad.h
FMS/mpp/include/mpp_do_update_nonblock.h
FMS/mpp/include/mpp_sum_nocomm_ad.h
FMS/mpp/include/mpp_update_nest_domains.h
FMS/mpp/include/mpp_sum_mpi_ad.h
FMS/mpp/include/mpp_reduce_mpi.h
FMS/mpp/include/mpp_gather.h
FMS/mpp/include/mpp_global_reduce.h
FMS/mpp/include/mpp_do_global_field_ad.h
FMS/mpp/include/mpp_transmit_sma.h
FMS/mpp/include/mpp_chksum_int.h
FMS/mpp/include/mpp_global_field_ug.h
FMS/mpp/include/mpp_do_updateV.h
FMS/mpp/include/mpp_global_sum_tl.h
FMS/mpp/include/mpp_chksum_scalar.h
FMS/mpp/include/mpp_write_compressed.h
FMS/mpp/include/mpp_sum_mpi.h
FMS/mpp/include/mpp_alltoall_mpi.h
FMS/mpp/include/mpp_error_s_a.h
FMS/mpp/include/mpp_do_updateV_nonblock.h
FMS/mpp/include/mpp_do_check.h
FMS/mpp/include/mpp_update_domains2D.h
FMS/mpp/include/mpp_sum_sma.h
FMS/mpp/include/mpp_group_update.h
FMS/mpp/include/mpp_get_boundary.h
FMS/mpp/include/mpp_error_a_s.h
FMS/mpp/include/mpp_get_boundary_ad.h
FMS/mpp/include/mpp_do_get_boundary.h
FMS/mpp/include/mpp_global_field.h
FMS/mpp/include/system_clock.h
FMS/mpp/include/mpp_type_mpi.h
FMS/mpp/include/mpp_transmit_nocomm.h
FMS/mpp/include/mpp_scatter.h
FMS/mpp/include/mpp_do_update_nest.h
FMS/mpp/include/mpp_read_2Ddecomp.h
FMS/mpp/include/mpp_error_s_s.h
FMS/mpp/include/mpp_global_sum_ad.h
FMS/mpp/include/mpp_update_domains2D_nonblock.h
FMS/mpp/include/mpp_do_update.h
FMS/mosaic/gradient_c2l.h
FMS/mosaic/interp.h
FMS/mosaic/mosaic_util.h
FMS/mosaic/constant.h
FMS/mosaic/read_mosaic.h
FMS/mosaic/create_xgrid.h
FMS/drifters/fms_switches.h
FMS/drifters/drifters_set_field.h
FMS/drifters/drifters_compute_k.h
FMS/drifters/drifters_push.h
FMS/include/fms_platform.h
FMS/include/file_version.h
)
