option(DEBUG       "Enable DEBUG mode" OFF)
option(REPRO       "Enable REPRO mode" OFF)
option(VERBOSE     "Enable VERBOSE mode" OFF)
option(32BIT       "Enable 32BIT (single precision arithmetic in dycore)" OFF)
option(OPENMP      "Enable OpenMP threading" ON)
option(AVX2        "Enable AVX2 instruction set" OFF)
option(INLINE_POST "Enable inline post" ON)
