option(DEBUG          "Enable DEBUG mode" OFF)
option(REPRO          "Enable REPRO mode" OFF)
option(VERBOSE        "Enable VERBOSE mode" OFF)
option(32BIT          "Enable 32BIT (single precision arithmetic in dycore)" OFF)
option(OPENMP         "Enable OpenMP threading" ON)
option(AVX2           "Enable AVX2 instruction set" ON)
option(QUAD_PRECISION "Enable QUAD_PRECISION (for certain grid metric terms in dycore)" ON)
option(INLINE_POST    "Enable inline post" OFF)
