option(32BIT           "Enable 32BIT (single precision arithmetic in dycore)" OFF)
option(AVX2            "Enable AVX2 instruction set" ON)
option(CCPP            "Enable CCPP" ON)
option(DEBUG           "Enable DEBUG mode" OFF)
option(INLINE_POST     "Enable inline post" ON)
option(MULTI_GASES     "Enable MULTI_GASES" OFF)
option(OPENMP          "Enable OpenMP threading" ON)
option(PARALLEL_NETCDF "Enable parallel NetCDF" OFF)
option(QUAD_PRECISION  "Enable QUAD_PRECISION (for certain grid metric terms in dycore)" ON)
option(REPRO           "Enable REPRO mode" OFF)
option(WW3             "Enable WW3" OFF)
