name: Stop runners

on:
  workflow_run:
    workflows: ["Pull request tests"]
    types:
      - completed

jobs:
  job1:
    name: Stop AWS runners
    runs-on: ubuntu-20.04

    steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Stop self-hosted runners
      env:
        aws_instance_id: ${{ secrets.AWS_INSTANCE_ID }}
      run: aws ec2 stop-instances --instance-ids $aws_instance_id
