# NOTE: This workflow can only be launched manually because it does not need to run on a PR 
# unless the PR updates the resource warnings workflow. If there is any issue launching it via the 
# GitHub Actions UI, it can be launched via the GitHub CLI: 
#    gh workflow run "Tests for the Regression Resource Check" --ref <branch-name>

name: Tests for the Regression Resource Check

on: workflow_dispatch

defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-tests:  
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout feature branch
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install pytest requests numpy pandas mdutils
          mkdir -p data
      - name: Run tests & publish output
        id: tests
        run: |
          cd .github/tests
          pytest > ./output.txt
          python ${{ github.workspace }}/.github/tests/print_test_summary.py >> $GITHUB_STEP_SUMMARY

