name: Update Project Labels
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled

jobs:
  baseline-labels:
    name: Baseline labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Lack of baseline labels
        if: | 
            !contains(github.event.pull_request.labels.*.name, 'No Baseline Change') && 
            !contains(github.event.pull_request.labels.*.name, 'Baseline Updates') && 
            !contains(github.event.pull_request.labels.*.name, 'New Baselines')
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: 'Baseline Changes'
          field-value: 'Unknown'
      - name: Contradictory labels
        if: | 
            contains(github.event.pull_request.labels.*.name, 'No Baseline Change') && 
            (contains(github.event.pull_request.labels.*.name, 'Baseline Updates') || 
            contains(github.event.pull_request.labels.*.name, 'New Baselines'))
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: 'Baseline Changes'
          field-value: 'Unknown'
      - name: Baseline changes labels
        if: |
            !contains(github.event.pull_request.labels.*.name, 'No Baseline Change') &&
            ( contains(github.event.pull_request.labels.*.name, 'Baseline Updates') || 
            contains(github.event.pull_request.labels.*.name, 'New Baselines') )
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: 'Baseline Changes'
          field-value: 'Yes'
      - name: No baseline changes label
        if: | 
            contains(github.event.pull_request.labels.*.name, 'No Baseline Change') && 
            !contains(github.event.pull_request.labels.*.name, 'Baseline Updates') && 
            !contains(github.event.pull_request.labels.*.name, 'New Baselines')
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: 'Baseline Changes'
          field-value: 'No'
  data-labels:
    name: Input data
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: New input data required
        if: |
          contains(github.event.pull_request.labels.*.name, 'New Input Data') &&
          !contains(github.event.pull_request.labels.*.name, 'Updated Input Data')
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: "Input Data Req'd"
          field-value: 'New'
      - name: Updated input data required
        if: |
          contains(github.event.pull_request.labels.*.name, 'Updated Input Data') &&
          !contains(github.event.pull_request.labels.*.name, 'New Input Data')
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: "Input Data Req'd"
          field-value: 'Updated'
      - name: No input data changes
        if: |
            (!contains(github.event.pull_request.labels.*.name, 'Updated Input Data')) && 
            (!contains(github.event.pull_request.labels.*.name, 'New Input Data'))
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: "Input Data Req'd"
          field-value: 'None'
      - name: Contradictory labels
        if: | 
            contains(github.event.pull_request.labels.*.name, 'Updated Input Data') &&
            contains(github.event.pull_request.labels.*.name, 'New Input Data')
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: "Input Data Req'd"
          field-value: 'Unknown'
  priority-labels:
    name: Priority
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Read Priority field
        uses: EndBug/project-fields@v2.1.0
        id: priority_field
        with:
          operation: get
          fields: Priority
          github_token: ${{ secrets.PR_PROJECT_TOKEN }}
          project_url: https://github.com/orgs/ufs-community/projects/70
          resource_url: ${{ github.event.pull_request.html_url }}
      - name: Assign value to Priority field
        id: assign_priority
        run: |
          PRIORITY="${{ steps.priority_field.outputs.values }}"
          echo "priority=$PRIORITY" >> $GITHUB_OUTPUT
      - name: Normal Priority
        if: |
            !contains(github.event.pull_request.labels.*.name, 'Priority: Critical') &&
            !contains(github.event.pull_request.labels.*.name, 'Priority: High') &&
            steps.assign_priority.outputs.priority != 'Combine'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: 'Priority'
          field-value: 'Normal'
      - name: Critical priority
        if: |
          contains(github.event.pull_request.labels.*.name, 'Priority: Critical') &&
          steps.assign_priority.outputs.priority != 'Combine'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: 'Priority'
          field-value: 'Critical'
      - name: High Priority
        if: |
            (contains(github.event.pull_request.labels.*.name, 'Priority: High')) &&
            steps.assign_priority.outputs.priority != 'Combine'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: 'Priority'
          field-value: 'High'
      - name: Unknown Priority
        if: |
            contains(github.event.pull_request.labels.*.name, 'Priority: Critical') &&
            contains(github.event.pull_request.labels.*.name, 'Priority: High')
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
          field-name: 'Priority'
          field-value: 'Unknown'
